### PR TITLE
fix(types): fissure, zariman, cambion syntax

### LINKED ISSUE #440: Incorrect type returned for fissure missions
**Summary (short):**

Incorrect type for fissure property in typescript projects
---
**Description:**

The type Array<News> is used instead of Array<Fissure>, however if we check the instance of the elements inside the array of worldstate.fissures is reporting correctly Fissure

---
**If issue, Reproduction:**

```typescript
// index.ts

import axios from 'axios'
import WorldState from 'warframe-worldstate-parser'

async function start(){
  const { data } = await axios.get('https://content.warframe.com/dynamic/worldState.php')
  const state = new WorldState(JSON.stringify(data))  
  
  state.fissures // This will be reported as Array<News>
}


```

---
**Evidence:**

image

### PR DESCRIPTION
**Pull request by FubyCoder**
### What did you fix? 
This PR fixes [#440](https://github.com/WFCD/warframe-worldstate-parser/issues/440)

closes #440 

---

### Reproduction steps

The error is already described in [#440](https://github.com/WFCD/warframe-worldstate-parser/issues/440)

A little summary : 

The type generated by the `build:types` command provided incorrect types for the property `fissures` in typescript projects, reporting this property as an array of News instead of Fissure

This PR fixes this minor issue

---

### Considerations
- Does this contain a new dependency? **[No]**
- Does this introduce opinionated data formatting or manual data entry? **[No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
- Have I run the linter? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**

### CODE REVIEW

File: lib/Fissure.js [hunk 1]
```diff
@@ -137,4 +137,6 @@ module.exports = class Fissure extends WorldstateObject {
   toString() {
     return `[${this.getETAString()}] ${this.tier} fissure at ${this.node} - ${this.enemy} ${this.missionType}`;
   }
-};
+}
+
+module.exports = Fissure;
```
Comment (TobiTenno) [inline lib/Fissure.js:142]: why?

Comment (TobiTenno) [reply lib/Fissure.js:142]: sorry, should've phrased it better.

why doesn't typescript resolve the type without this

Comment (FubyCoder) [reply lib/Fissure.js:142]: This fixes issue with typescript type resolution, moving the export away from the declaration of the class fixes the issue

Here is another example with other classes that typescript has problem to resolve due to the syntax 

`module.exports = class ZarimanCycle`

image

Comment (TobiTenno) [reply lib/Fissure.js:142]: yeah, i was already committing that one to your branch, lol. gg typescript not working right.

**Review by TobiTenno — APPROVED** [review]
